### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by arnoudbuzing** [wjxway/Realistic_Blackhole_Accretion_Disk#1]
Very nicely done! Have you considered posting about this on the Wolfram Community pages (https://community.wolfram.com) ? I think many Mathematica users would be interested to see this very nice analysis!

**Comment by wjxway** [comment]
Sure, I'm writing a blog post like stuff to introduce it more thoroughly, I certainly can post it on wolfram community~

**Comment by wjxway** [comment]
https://community.wolfram.com/groups/-/m/t/2017849?p_p_auth=dy7ScqEd

**Comment by arnoudbuzing** [comment]
Awesome, thanks!!!
